# Generated by Django 4.0 on 2021-12-23 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_alter_farmer_details_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pro_availability',
            new_name='pro_quantity',
        ),
    ]
