# Generated by Django 4.0 on 2022-01-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_rename_pro_availability_product_pro_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer_details',
            old_name='state',
            new_name='city',
        ),
        migrations.AddField(
            model_name='farmer_details',
            name='pincode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
