# Generated by Django 4.0 on 2022-01-08 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_rename_state_farmer_details_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='farmer_id',
        ),
        migrations.DeleteModel(
            name='farmer_details',
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
