# Generated by Django 4.0 on 2022-01-10 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('pro_description', models.CharField(max_length=200)),
                ('pro_category', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=100)),
                ('pro_quantity', models.CharField(max_length=100)),
                ('pic', models.FileField(upload_to='media/agroproduct')),
                ('enable', models.CharField(default='Enable', max_length=100)),
                ('agro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer_details')),
            ],
        ),
    ]
