# Generated by Django 4.0 on 2022-01-11 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0009_alter_product_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='far_id',
        ),
        migrations.DeleteModel(
            name='farmer_details',
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
