# Generated by Django 4.0 on 2022-01-11 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0012_customer_details'),
        ('farmer', '0010_remove_product_far_id_delete_farmer_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmer_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dod', models.CharField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('pincode', models.CharField(max_length=100, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.user')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('pro_description', models.CharField(max_length=200)),
                ('pro_category', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=100)),
                ('pro_quantity', models.CharField(max_length=100)),
                ('pic', models.FileField(upload_to='media/farproduct')),
                ('enable', models.CharField(default='Enable', max_length=100)),
                ('far_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer_details')),
            ],
        ),
    ]
