# Generated by Django 4.0 on 2022-01-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0014_alter_faraddtocart_p_id_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer_details',
            name='img',
            field=models.FileField(default='media/profile/default.png', upload_to='media/profile'),
        ),
    ]
