# Generated by Django 4.0 on 2022-01-18 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agroshop', '0041_agroproduct_remove_product_user_id'),
        ('farmer', '0015_farmer_details_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faraddtocart',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroshop.agroproduct'),
        ),
    ]
