# Generated by Django 4.0 on 2022-01-18 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agroshop', '0043_alter_agroproduct_pic'),
        ('customer', '0012_customer_details'),
        ('farmer', '0017_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='farwishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroshop.agroproduct')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.user')),
            ],
        ),
    ]
