# Generated by Django 4.0 on 2022-01-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0018_farwishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='faraddtocart',
            name='qty',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faraddtocart',
            name='total_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
