# Generated by Django 4.0 on 2022-01-22 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_customer_details_img'),
        ('farmer', '0019_faraddtocart_qty_faraddtocart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='far_id',
        ),
        migrations.AddField(
            model_name='product',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.user'),
            preserve_default=False,
        ),
    ]
