# Generated by Django 4.0 on 2022-01-22 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0022_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer_details',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='farwishlist',
            name='p_id',
        ),
        migrations.RemoveField(
            model_name='farwishlist',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='faraddtocart',
        ),
        migrations.DeleteModel(
            name='farmer_details',
        ),
        migrations.DeleteModel(
            name='farwishlist',
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
