# Generated by Django 4.0 on 2022-02-20 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0030_order_cus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order_cus',
        ),
    ]
