# Generated by Django 4.0 on 2022-01-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agro_details',
            old_name='state',
            new_name='city',
        ),
        migrations.AddField(
            model_name='agro_details',
            name='pincode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
