# Generated by Django 4.0 on 2022-01-08 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0006_customer_details'),
        ('agroshop', '0004_remove_agroproduct_agro_id_delete_agro_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='agro_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dod', models.CharField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('pincode', models.CharField(max_length=100, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.user')),
            ],
        ),
        migrations.CreateModel(
            name='agroproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('pro_description', models.CharField(max_length=200)),
                ('pro_category', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=100)),
                ('pro_quantity', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='media/agroproduct')),
                ('agro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroshop.agro_details')),
            ],
        ),
    ]
