# Generated by Django 4.0 on 2022-01-08 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroshop', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agroproduct',
            name='agro_id',
        ),
        migrations.DeleteModel(
            name='agro_details',
        ),
        migrations.DeleteModel(
            name='agroproduct',
        ),
    ]
