# Generated by Django 4.0 on 2022-01-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroshop', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agroproduct',
            name='enable',
            field=models.CharField(default='Enable', max_length=100),
        ),
    ]
