# Generated by Django 4.0 on 2022-01-08 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroshop', '0009_alter_agroproduct_product_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='agroproduct',
        ),
    ]
