# Generated by Django 4.0 on 2022-01-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroshop', '0011_agroproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agroproduct',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
    ]
