# Generated by Django 4.0 on 2022-01-08 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroshop', '0012_alter_agroproduct_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agroproduct',
            old_name='image',
            new_name='pic',
        ),
    ]
