# Generated by Django 4.0 on 2022-01-08 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroshop', '0013_rename_image_agroproduct_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='agroproduct',
        ),
    ]
