# Generated by Django 4.0 on 2022-01-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroshop', '0015_agroproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='agroproduct',
        ),
    ]
