# Generated by Django 4.0 on 2022-01-10 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroshop', '0017_agroproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='agroproduct',
        ),
    ]
