# Generated by Django 4.0 on 2022-01-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroshop', '0019_agroproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='agro_details',
            name='img',
            field=models.FileField(default='media/profile/default', upload_to='media/profile/agro'),
        ),
    ]
