# Generated by Django 4.0 on 2022-01-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroshop', '0021_alter_agro_details_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agro_details',
            name='img',
            field=models.FileField(default='media/default', upload_to='media/profile/agro'),
        ),
    ]
