# Generated by Django 4.0 on 2022-01-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroshop', '0024_agro_details_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agro_details',
            name='img',
            field=models.FileField(upload_to='media/profile'),
        ),
    ]
