# Generated by Django 4.0 on 2022-01-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroshop', '0034_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agro_details',
            name='img',
            field=models.FileField(default='media/profile/default.png', upload_to='media/profile'),
        ),
    ]
