# Generated by Django 4.0 on 2022-01-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroshop', '0039_delete_agroproduct_product_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pic',
            field=models.FileField(upload_to='media/product'),
        ),
    ]
