# Generated by Django 4.0 on 2022-01-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroshop', '0042_delete_product_agroproduct_agro_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agroproduct',
            name='pic',
            field=models.FileField(upload_to='media/agroproduct'),
        ),
    ]
