# Generated by Django 4.0 on 2022-01-31 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroshop', '0046_order_a'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order_a',
        ),
    ]
