# Generated by Django 4.0 on 2022-01-31 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_initial'),
        ('agroshop', '0047_delete_order_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('totalpri', models.CharField(max_length=100)),
                ('seller_id', models.CharField(max_length=100)),
                ('orderdate', models.DateTimeField(auto_now_add=True)),
                ('cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.user')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroshop.agroproduct')),
            ],
        ),
    ]
