# Generated by Django 4.0 on 2022-01-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroshop', '0052_alter_order_a_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_a',
            name='orderdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
