# Generated by Django 4.0 on 2022-01-31 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroshop', '0057_alter_order_a_orderdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_a',
            name='orderdate',
        ),
    ]
