# Generated by Django 4.0 on 2022-01-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroshop', '0058_remove_order_a_orderdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_a',
            name='orderdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
