# Generated by Django 4.0 on 2022-02-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroshop', '0059_order_a_orderdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_a',
            name='orderdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
