# Generated by Django 4.0 on 2022-01-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_user_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_details',
            old_name='state',
            new_name='city',
        ),
        migrations.AddField(
            model_name='customer_details',
            name='pincode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
