# Generated by Django 4.0 on 2022-01-08 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_rename_state_customer_details_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer_details',
        ),
    ]
