# Generated by Django 4.0 on 2022-01-08 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0003_delete_nursery_details'),
        ('farmer', '0005_remove_product_farmer_id_delete_farmer_details_and_more'),
        ('agroshop', '0006_remove_agroproduct_agro_id_delete_agro_details_and_more'),
        ('customer', '0006_customer_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer_details',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
