# Generated by Django 4.0 on 2022-01-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_customer_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_details',
            name='img',
            field=models.FileField(default='media/profile/default.png', upload_to='media/profile'),
        ),
    ]
