# Generated by Django 4.0 on 2022-01-22 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0013_delete_nursery_details'),
        ('farmer', '0023_remove_farmer_details_user_id_and_more'),
        ('agroshop', '0044_remove_agroproduct_agro_id_delete_agro_details_and_more'),
        ('customer', '0013_customer_details_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer_details',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
