# Generated by Django 4.0 on 2022-01-10 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0005_nurproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurproduct',
            old_name='far_id',
            new_name='nur_id',
        ),
    ]
