# Generated by Django 4.0 on 2022-01-18 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nurproduct',
        ),
    ]
