# Generated by Django 4.0 on 2022-01-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0010_nurproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursery_details',
            name='img',
            field=models.FileField(default='media/profile/default.png', upload_to='media/profile'),
        ),
    ]
