# Generated by Django 4.0 on 2022-01-22 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0011_nursery_details_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nurproduct',
        ),
    ]
