# Generated by Django 4.0 on 2022-01-22 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0012_delete_nurproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nursery_details',
        ),
    ]
